language: ruby

rvm:
  - 2.3.3

install:
  - bundle install --path vendor/bundle

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer _site --empty-alt-ignore --disable-external

# branch whitelist
branches:
  only:
    - master
    
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# route your build to the container-based infrastructure for a faster build
sudo: false 
